# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openai.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import result_pb2 as result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0copenai.proto\x12\x06openai\x1a\x0cresult.proto\">\n\x0b\x43hatRequest\x12\x0e\n\x06\x61pikey\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\"\x1e\n\x0cModelRequest\x12\x0e\n\x06\x61pikey\x18\x01 \x01(\t\",\n\rModelResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63reated\x18\x02 \x01(\x03\":\n\x11ModelResponseList\x12%\n\x06models\x18\x01 \x03(\x0b\x32\x15.openai.ModelResponse2m\n\x06OpenAI\x12\x34\n\nget_models\x12\x14.openai.ModelRequest\x1a\x10.result.Response\x12-\n\x04\x63hat\x12\x13.openai.ChatRequest\x1a\x10.result.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openai_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CHATREQUEST']._serialized_start=38
  _globals['_CHATREQUEST']._serialized_end=100
  _globals['_MODELREQUEST']._serialized_start=102
  _globals['_MODELREQUEST']._serialized_end=132
  _globals['_MODELRESPONSE']._serialized_start=134
  _globals['_MODELRESPONSE']._serialized_end=178
  _globals['_MODELRESPONSELIST']._serialized_start=180
  _globals['_MODELRESPONSELIST']._serialized_end=238
  _globals['_OPENAI']._serialized_start=240
  _globals['_OPENAI']._serialized_end=349
# @@protoc_insertion_point(module_scope)
